# Install pre-commit hooks via
# pre-commit install

exclude: >
    (?x)^(
      \.vscode/settings\.json|
      tests/commonmark/commonmark\.json|
      .*\.xml|
      tests/.*\.txt
    )$

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.47"
    hooks:
    - id: check-manifest
      args: [--no-build-isolation]
      additional_dependencies: [setuptools>=46.4.0]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    - id: pyupgrade
      args: [--py37-plus]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      additional_dependencies: [flake8-bugbear==21.3.1]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
    - id: mypy
      args: [--config-file=setup.cfg]
      additional_dependencies:
      - importlib_metadata
      - myst-parser~=0.17.0
      - "sphinx~=4.3.2"
      - types-PyYAML
      files: >
        (?x)^(
            myst_nb/[^/]+.py|
        )$
